/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    'menu-categories': MenuCategory;
    'menu-items': MenuItem;
    media: Media;
    sections: Section;
    tables: Table;
    orders: Order;
    reservations: Reservation;
    'contact-messages': ContactMessage;
    admins: Admin;
    restaurants: Restaurant;
    'site-content': SiteContent;
    videos: Video;
    promotions: Promotion;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'menu-categories': MenuCategoriesSelect<false> | MenuCategoriesSelect<true>;
    'menu-items': MenuItemsSelect<false> | MenuItemsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    tables: TablesSelect<false> | TablesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    reservations: ReservationsSelect<false> | ReservationsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    admins: AdminsSelect<false> | AdminsSelect<true>;
    restaurants: RestaurantsSelect<false> | RestaurantsSelect<true>;
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr' | 'nl') | ('en' | 'fr' | 'nl')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'fr' | 'nl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories".
 */
export interface MenuCategory {
  id: number;
  name: string;
  /**
   * Which restaurant this category belongs to
   */
  restaurant?: ('my-restaurant' | 'verde-kitchen') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items".
 */
export interface MenuItem {
  id: number;
  name: string;
  description: string;
  price: number;
  /**
   * Which restaurant this item belongs to
   */
  restaurant?: ('my-restaurant' | 'verde-kitchen') | null;
  /**
   * 6% food · 12% restaurant meals · 21% alcohol / standard
   */
  vatRate: number;
  /**
   * Uncheck to hide this item from the menu
   */
  available?: boolean | null;
  category: number | MenuCategory;
  /**
   * Optional dish photo
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Auto-populated on upload
   */
  restaurant?: ('my-restaurant' | 'verde-kitchen') | null;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Named areas of your restaurant (e.g. Main Floor, Patio, Bar).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: number;
  name: string;
  restaurant?: ('my-restaurant' | 'verde-kitchen') | null;
  /**
   * Display order — lower numbers appear first.
   */
  order?: number | null;
  /**
   * Uncheck to hide this section from the booking page.
   */
  isActive?: boolean | null;
  /**
   * Upload a floor plan image. Tables will be positioned on top of it using percentage coordinates.
   */
  backgroundImage?: (number | null) | Media;
  /**
   * The reference width used when placing tables. Positions are stored as % of this value.
   */
  canvasWidth?: number | null;
  /**
   * The reference height used when placing tables. Positions are stored as % of this value.
   */
  canvasHeight?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual tables. Position them using percentage coordinates on the floor plan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tables".
 */
export interface Table {
  id: number;
  /**
   * Shown to customers when they hover or select the table.
   */
  label: string;
  restaurant?: ('my-restaurant' | 'verde-kitchen') | null;
  /**
   * Which section/area this table belongs to.
   */
  section: number | Section;
  /**
   * Maximum number of guests this table seats.
   */
  capacity: number;
  /**
   * Visual shape shown on the floor plan.
   */
  shape: 'round' | 'square' | 'rectangle';
  /**
   * Horizontal centre of the table as % of canvas width (0 = left, 100 = right).
   */
  x: number;
  /**
   * Vertical centre of the table as % of canvas height (0 = top, 100 = bottom).
   */
  y: number;
  /**
   * Table width as % of canvas width.
   */
  width: number;
  /**
   * Table height as % of canvas height. For round/square tables, keep equal to width.
   */
  height: number;
  /**
   * Uncheck to mark this table as unavailable (shown greyed out on the floor plan).
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  restaurant?: ('my-restaurant' | 'verde-kitchen') | null;
  type: 'takeaway' | 'eat-in' | 'delivery';
  status: 'pending' | 'preparing' | 'ready' | 'completed' | 'cancelled';
  customer: {
    name: string;
    phone: string;
    email?: string | null;
  };
  items: {
    name: string;
    price: number;
    quantity: number;
    vatRate?: number | null;
    id?: string | null;
  }[];
  /**
   * Auto-calculated from items
   */
  total: number;
  tableNumber?: string | null;
  pickupTime?: string | null;
  delivery?: {
    street?: string | null;
    city?: string | null;
    postalCode?: string | null;
    instructions?: string | null;
  };
  /**
   * Leave empty for ASAP orders. Set a date/time for future orders.
   */
  scheduledFor?: string | null;
  notes?: string | null;
  paymentMethod?: ('cash' | 'card') | null;
  stripeSessionId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations".
 */
export interface Reservation {
  id: number;
  /**
   * Auto-populated from the app's API key
   */
  restaurant: 'my-restaurant' | 'verde-kitchen';
  name: string;
  email: string;
  phone: string;
  date: string;
  partySize: number;
  /**
   * General = name/time only. Table = specific floor plan table selected.
   */
  type: 'general' | 'table';
  /**
   * The specific table the guest selected on the floor plan.
   */
  table?: (number | null) | Table;
  notes?: string | null;
  status: 'PENDING' | 'CONFIRMED' | 'CANCELLED';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  /**
   * Auto-populated from the app's API key
   */
  restaurant: 'my-restaurant' | 'verde-kitchen';
  name: string;
  email: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  /**
   * Scope this admin to a single restaurant. Leave blank for full access (super-admin).
   */
  restaurant?: ('my-restaurant' | 'verde-kitchen') | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants".
 */
export interface Restaurant {
  id: number;
  name: string;
  slug: 'my-restaurant' | 'verde-kitchen';
  type: 'eat-in' | 'takeaway';
  /**
   * Enable online ordering and Stripe payments for this restaurant
   */
  onlineOrdering?: boolean | null;
  /**
   * Stripe secret key (sk_live_... or sk_test_...) from the restaurant's Stripe dashboard
   */
  stripeSecretKey?: string | null;
  /**
   * Stripe webhook signing secret (whsec_...) — register webhook URL as: /api/webhooks/stripe/<slug>
   */
  stripeWebhookSecret?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: number;
  restaurant?: ('my-restaurant' | 'verde-kitchen') | null;
  tagline?: string | null;
  /**
   * Short description shown in hero or meta tags
   */
  description?: string | null;
  /**
   * About / our story section
   */
  story?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown as fallback when no video is set
   */
  heroImage?: (number | null) | Media;
  /**
   * Optional background video for the hero section (MP4 recommended)
   */
  heroVideo?: (number | null) | Video;
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  openingHours?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        open?: string | null;
        close?: string | null;
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'facebook' | 'tiktok' | 'twitter';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  restaurant?: ('my-restaurant' | 'verde-kitchen') | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  restaurant?: ('my-restaurant' | 'verde-kitchen') | null;
  /**
   * Uncheck to hide this promotion
   */
  active?: boolean | null;
  /**
   * Optional banner image
   */
  image?: (number | null) | Media;
  /**
   * Show from this date (leave empty to show immediately)
   */
  startDate?: string | null;
  /**
   * Auto-hide after this date (leave empty to show indefinitely)
   */
  endDate?: string | null;
  /**
   * Days before re-showing after dismissal. 0 = never re-show.
   */
  dismissDays?: number | null;
  title: string;
  message?: string | null;
  /**
   * e.g. "Order Now"
   */
  ctaLabel?: string | null;
  /**
   * Link for the CTA button
   */
  ctaUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'menu-categories';
        value: number | MenuCategory;
      } | null)
    | ({
        relationTo: 'menu-items';
        value: number | MenuItem;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sections';
        value: number | Section;
      } | null)
    | ({
        relationTo: 'tables';
        value: number | Table;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'reservations';
        value: number | Reservation;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'restaurants';
        value: number | Restaurant;
      } | null)
    | ({
        relationTo: 'site-content';
        value: number | SiteContent;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-categories_select".
 */
export interface MenuCategoriesSelect<T extends boolean = true> {
  name?: T;
  restaurant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-items_select".
 */
export interface MenuItemsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  price?: T;
  restaurant?: T;
  vatRate?: T;
  available?: T;
  category?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  restaurant?: T;
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  name?: T;
  restaurant?: T;
  order?: T;
  isActive?: T;
  backgroundImage?: T;
  canvasWidth?: T;
  canvasHeight?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tables_select".
 */
export interface TablesSelect<T extends boolean = true> {
  label?: T;
  restaurant?: T;
  section?: T;
  capacity?: T;
  shape?: T;
  x?: T;
  y?: T;
  width?: T;
  height?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  restaurant?: T;
  type?: T;
  status?: T;
  customer?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
      };
  items?:
    | T
    | {
        name?: T;
        price?: T;
        quantity?: T;
        vatRate?: T;
        id?: T;
      };
  total?: T;
  tableNumber?: T;
  pickupTime?: T;
  delivery?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        instructions?: T;
      };
  scheduledFor?: T;
  notes?: T;
  paymentMethod?: T;
  stripeSessionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reservations_select".
 */
export interface ReservationsSelect<T extends boolean = true> {
  restaurant?: T;
  name?: T;
  email?: T;
  phone?: T;
  date?: T;
  partySize?: T;
  type?: T;
  table?: T;
  notes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  restaurant?: T;
  name?: T;
  email?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  restaurant?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants_select".
 */
export interface RestaurantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  onlineOrdering?: T;
  stripeSecretKey?: T;
  stripeWebhookSecret?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  restaurant?: T;
  tagline?: T;
  description?: T;
  story?: T;
  heroImage?: T;
  heroVideo?: T;
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  openingHours?:
    | T
    | {
        day?: T;
        open?: T;
        close?: T;
        closed?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  restaurant?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  restaurant?: T;
  active?: T;
  image?: T;
  startDate?: T;
  endDate?: T;
  dismissDays?: T;
  title?: T;
  message?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}